defaultTasks 'clean', 'test', 'aggregate'

repositories {
    mavenCentral()
}

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "net.serenity-bdd:serenity-gradle-plugin:3.6.7"
        //classpath "net.serenity-bdd:serenity-gradle-plugin:3.5.0"
    }
}


apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: "net.serenity-bdd.serenity-gradle-plugin"

sourceCompatibility = 1.9
targetCompatibility = 1.9

ext {
    slf4jVersion = '2.0.9'
    serenityCoreVersion = '4.0.28'
    serenityCucumberVersion = '4.0.28'
    junitVersion = '4.13.1'
    assertJVersion = '3.24.1'
    logbackVersion = '1.4.14'
}

dependencies {
    implementation "ch.qos.logback:logback-classic:${logbackVersion}"

    testImplementation "net.serenity-bdd:serenity-core:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-cucumber:${serenityCucumberVersion}",
            "net.serenity-bdd:serenity-screenplay:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-screenplay-webdriver:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-ensure:${serenityCoreVersion}",
            "junit:junit:${junitVersion}",
            "org.junit.platform:junit-platform-launcher:1.8.2",
            "org.junit.jupiter:junit-jupiter-engine:5.8.2",
            "org.junit.vintage:junit-vintage-engine:5.8.2",
            "org.assertj:assertj-core:${assertJVersion}"
    implementation group: 'org.apache.poi', name: 'poi-ooxml', version: '4.0.0'
    implementation group: 'org.apache.poi', name: 'poi', version: '4.0.0'


}

test {
    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
}

serenity {
    // Specify the root package of any JUnit acceptance tests to appear in the Serenity report
    testRoot = "starter"
    // Specify the root directory of any Cucumber feature files
    requirementsDir = "src/test/resources/features"
    reports = ["single-page-html"]

}

gradle.startParameter.continueOnFailure = true

test.finalizedBy(aggregate)